// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gameserver.proto

package com.protobuf.game;

public final class GameServer {
  private GameServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlayerEnterGameRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PlayerEnterGameRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 玩家id
     * </pre>
     *
     * <code>int64 playerId = 1;</code>
     */
    long getPlayerId();
  }
  /**
   * <pre>
   *PLAYER_ENTER_GAME_REQUEST = 0x20001;// 玩家进入游戏服请求
   * </pre>
   *
   * Protobuf type {@code PlayerEnterGameRequest}
   */
  public  static final class PlayerEnterGameRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PlayerEnterGameRequest)
      PlayerEnterGameRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlayerEnterGameRequest.newBuilder() to construct.
    private PlayerEnterGameRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerEnterGameRequest() {
      playerId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerEnterGameRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              playerId_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protobuf.game.GameServer.internal_static_PlayerEnterGameRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protobuf.game.GameServer.internal_static_PlayerEnterGameRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protobuf.game.GameServer.PlayerEnterGameRequest.class, com.protobuf.game.GameServer.PlayerEnterGameRequest.Builder.class);
    }

    public static final int PLAYERID_FIELD_NUMBER = 1;
    private long playerId_;
    /**
     * <pre>
     * 玩家id
     * </pre>
     *
     * <code>int64 playerId = 1;</code>
     */
    public long getPlayerId() {
      return playerId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (playerId_ != 0L) {
        output.writeInt64(1, playerId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (playerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, playerId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.protobuf.game.GameServer.PlayerEnterGameRequest)) {
        return super.equals(obj);
      }
      com.protobuf.game.GameServer.PlayerEnterGameRequest other = (com.protobuf.game.GameServer.PlayerEnterGameRequest) obj;

      boolean result = true;
      result = result && (getPlayerId()
          == other.getPlayerId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPlayerId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.protobuf.game.GameServer.PlayerEnterGameRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.game.GameServer.PlayerEnterGameRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.game.GameServer.PlayerEnterGameRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.game.GameServer.PlayerEnterGameRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.game.GameServer.PlayerEnterGameRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.game.GameServer.PlayerEnterGameRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.game.GameServer.PlayerEnterGameRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protobuf.game.GameServer.PlayerEnterGameRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protobuf.game.GameServer.PlayerEnterGameRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.protobuf.game.GameServer.PlayerEnterGameRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protobuf.game.GameServer.PlayerEnterGameRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protobuf.game.GameServer.PlayerEnterGameRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.protobuf.game.GameServer.PlayerEnterGameRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *PLAYER_ENTER_GAME_REQUEST = 0x20001;// 玩家进入游戏服请求
     * </pre>
     *
     * Protobuf type {@code PlayerEnterGameRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PlayerEnterGameRequest)
        com.protobuf.game.GameServer.PlayerEnterGameRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protobuf.game.GameServer.internal_static_PlayerEnterGameRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protobuf.game.GameServer.internal_static_PlayerEnterGameRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protobuf.game.GameServer.PlayerEnterGameRequest.class, com.protobuf.game.GameServer.PlayerEnterGameRequest.Builder.class);
      }

      // Construct using com.protobuf.game.GameServer.PlayerEnterGameRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        playerId_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protobuf.game.GameServer.internal_static_PlayerEnterGameRequest_descriptor;
      }

      @java.lang.Override
      public com.protobuf.game.GameServer.PlayerEnterGameRequest getDefaultInstanceForType() {
        return com.protobuf.game.GameServer.PlayerEnterGameRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.protobuf.game.GameServer.PlayerEnterGameRequest build() {
        com.protobuf.game.GameServer.PlayerEnterGameRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.protobuf.game.GameServer.PlayerEnterGameRequest buildPartial() {
        com.protobuf.game.GameServer.PlayerEnterGameRequest result = new com.protobuf.game.GameServer.PlayerEnterGameRequest(this);
        result.playerId_ = playerId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protobuf.game.GameServer.PlayerEnterGameRequest) {
          return mergeFrom((com.protobuf.game.GameServer.PlayerEnterGameRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protobuf.game.GameServer.PlayerEnterGameRequest other) {
        if (other == com.protobuf.game.GameServer.PlayerEnterGameRequest.getDefaultInstance()) return this;
        if (other.getPlayerId() != 0L) {
          setPlayerId(other.getPlayerId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protobuf.game.GameServer.PlayerEnterGameRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protobuf.game.GameServer.PlayerEnterGameRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long playerId_ ;
      /**
       * <pre>
       * 玩家id
       * </pre>
       *
       * <code>int64 playerId = 1;</code>
       */
      public long getPlayerId() {
        return playerId_;
      }
      /**
       * <pre>
       * 玩家id
       * </pre>
       *
       * <code>int64 playerId = 1;</code>
       */
      public Builder setPlayerId(long value) {
        
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 玩家id
       * </pre>
       *
       * <code>int64 playerId = 1;</code>
       */
      public Builder clearPlayerId() {
        
        playerId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PlayerEnterGameRequest)
    }

    // @@protoc_insertion_point(class_scope:PlayerEnterGameRequest)
    private static final com.protobuf.game.GameServer.PlayerEnterGameRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.protobuf.game.GameServer.PlayerEnterGameRequest();
    }

    public static com.protobuf.game.GameServer.PlayerEnterGameRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerEnterGameRequest>
        PARSER = new com.google.protobuf.AbstractParser<PlayerEnterGameRequest>() {
      @java.lang.Override
      public PlayerEnterGameRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerEnterGameRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerEnterGameRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerEnterGameRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.protobuf.game.GameServer.PlayerEnterGameRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PlayerEnterGameResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PlayerEnterGameResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 玩家id
     * </pre>
     *
     * <code>int64 playerId = 1;</code>
     */
    long getPlayerId();

    /**
     * <pre>
     * 玩家钻石
     * </pre>
     *
     * <code>int64 diamond = 2;</code>
     */
    long getDiamond();

    /**
     * <pre>
     * 玩家金币
     * </pre>
     *
     * <code>int64 gold = 3;</code>
     */
    long getGold();

    /**
     * <pre>
     * 玩家昵称
     * </pre>
     *
     * <code>string playerName = 4;</code>
     */
    java.lang.String getPlayerName();
    /**
     * <pre>
     * 玩家昵称
     * </pre>
     *
     * <code>string playerName = 4;</code>
     */
    com.google.protobuf.ByteString
        getPlayerNameBytes();

    /**
     * <pre>
     * 头像路径
     * </pre>
     *
     * <code>string avatarPath = 5;</code>
     */
    java.lang.String getAvatarPath();
    /**
     * <pre>
     * 头像路径
     * </pre>
     *
     * <code>string avatarPath = 5;</code>
     */
    com.google.protobuf.ByteString
        getAvatarPathBytes();
  }
  /**
   * <pre>
   *PLAYER_ENTER_GAME_RESPONSE = 0x20002;// 玩家进入游戏服返回
   * </pre>
   *
   * Protobuf type {@code PlayerEnterGameResponse}
   */
  public  static final class PlayerEnterGameResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PlayerEnterGameResponse)
      PlayerEnterGameResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlayerEnterGameResponse.newBuilder() to construct.
    private PlayerEnterGameResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerEnterGameResponse() {
      playerId_ = 0L;
      diamond_ = 0L;
      gold_ = 0L;
      playerName_ = "";
      avatarPath_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerEnterGameResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              playerId_ = input.readInt64();
              break;
            }
            case 16: {

              diamond_ = input.readInt64();
              break;
            }
            case 24: {

              gold_ = input.readInt64();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              playerName_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              avatarPath_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protobuf.game.GameServer.internal_static_PlayerEnterGameResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protobuf.game.GameServer.internal_static_PlayerEnterGameResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protobuf.game.GameServer.PlayerEnterGameResponse.class, com.protobuf.game.GameServer.PlayerEnterGameResponse.Builder.class);
    }

    public static final int PLAYERID_FIELD_NUMBER = 1;
    private long playerId_;
    /**
     * <pre>
     * 玩家id
     * </pre>
     *
     * <code>int64 playerId = 1;</code>
     */
    public long getPlayerId() {
      return playerId_;
    }

    public static final int DIAMOND_FIELD_NUMBER = 2;
    private long diamond_;
    /**
     * <pre>
     * 玩家钻石
     * </pre>
     *
     * <code>int64 diamond = 2;</code>
     */
    public long getDiamond() {
      return diamond_;
    }

    public static final int GOLD_FIELD_NUMBER = 3;
    private long gold_;
    /**
     * <pre>
     * 玩家金币
     * </pre>
     *
     * <code>int64 gold = 3;</code>
     */
    public long getGold() {
      return gold_;
    }

    public static final int PLAYERNAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object playerName_;
    /**
     * <pre>
     * 玩家昵称
     * </pre>
     *
     * <code>string playerName = 4;</code>
     */
    public java.lang.String getPlayerName() {
      java.lang.Object ref = playerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        playerName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 玩家昵称
     * </pre>
     *
     * <code>string playerName = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPlayerNameBytes() {
      java.lang.Object ref = playerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AVATARPATH_FIELD_NUMBER = 5;
    private volatile java.lang.Object avatarPath_;
    /**
     * <pre>
     * 头像路径
     * </pre>
     *
     * <code>string avatarPath = 5;</code>
     */
    public java.lang.String getAvatarPath() {
      java.lang.Object ref = avatarPath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        avatarPath_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 头像路径
     * </pre>
     *
     * <code>string avatarPath = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAvatarPathBytes() {
      java.lang.Object ref = avatarPath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        avatarPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (playerId_ != 0L) {
        output.writeInt64(1, playerId_);
      }
      if (diamond_ != 0L) {
        output.writeInt64(2, diamond_);
      }
      if (gold_ != 0L) {
        output.writeInt64(3, gold_);
      }
      if (!getPlayerNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, playerName_);
      }
      if (!getAvatarPathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, avatarPath_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (playerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, playerId_);
      }
      if (diamond_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, diamond_);
      }
      if (gold_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, gold_);
      }
      if (!getPlayerNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, playerName_);
      }
      if (!getAvatarPathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, avatarPath_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.protobuf.game.GameServer.PlayerEnterGameResponse)) {
        return super.equals(obj);
      }
      com.protobuf.game.GameServer.PlayerEnterGameResponse other = (com.protobuf.game.GameServer.PlayerEnterGameResponse) obj;

      boolean result = true;
      result = result && (getPlayerId()
          == other.getPlayerId());
      result = result && (getDiamond()
          == other.getDiamond());
      result = result && (getGold()
          == other.getGold());
      result = result && getPlayerName()
          .equals(other.getPlayerName());
      result = result && getAvatarPath()
          .equals(other.getAvatarPath());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPlayerId());
      hash = (37 * hash) + DIAMOND_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDiamond());
      hash = (37 * hash) + GOLD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getGold());
      hash = (37 * hash) + PLAYERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerName().hashCode();
      hash = (37 * hash) + AVATARPATH_FIELD_NUMBER;
      hash = (53 * hash) + getAvatarPath().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.protobuf.game.GameServer.PlayerEnterGameResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.game.GameServer.PlayerEnterGameResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.game.GameServer.PlayerEnterGameResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.game.GameServer.PlayerEnterGameResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.game.GameServer.PlayerEnterGameResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.game.GameServer.PlayerEnterGameResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.game.GameServer.PlayerEnterGameResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protobuf.game.GameServer.PlayerEnterGameResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protobuf.game.GameServer.PlayerEnterGameResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.protobuf.game.GameServer.PlayerEnterGameResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protobuf.game.GameServer.PlayerEnterGameResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protobuf.game.GameServer.PlayerEnterGameResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.protobuf.game.GameServer.PlayerEnterGameResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *PLAYER_ENTER_GAME_RESPONSE = 0x20002;// 玩家进入游戏服返回
     * </pre>
     *
     * Protobuf type {@code PlayerEnterGameResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PlayerEnterGameResponse)
        com.protobuf.game.GameServer.PlayerEnterGameResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protobuf.game.GameServer.internal_static_PlayerEnterGameResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protobuf.game.GameServer.internal_static_PlayerEnterGameResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protobuf.game.GameServer.PlayerEnterGameResponse.class, com.protobuf.game.GameServer.PlayerEnterGameResponse.Builder.class);
      }

      // Construct using com.protobuf.game.GameServer.PlayerEnterGameResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        playerId_ = 0L;

        diamond_ = 0L;

        gold_ = 0L;

        playerName_ = "";

        avatarPath_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protobuf.game.GameServer.internal_static_PlayerEnterGameResponse_descriptor;
      }

      @java.lang.Override
      public com.protobuf.game.GameServer.PlayerEnterGameResponse getDefaultInstanceForType() {
        return com.protobuf.game.GameServer.PlayerEnterGameResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.protobuf.game.GameServer.PlayerEnterGameResponse build() {
        com.protobuf.game.GameServer.PlayerEnterGameResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.protobuf.game.GameServer.PlayerEnterGameResponse buildPartial() {
        com.protobuf.game.GameServer.PlayerEnterGameResponse result = new com.protobuf.game.GameServer.PlayerEnterGameResponse(this);
        result.playerId_ = playerId_;
        result.diamond_ = diamond_;
        result.gold_ = gold_;
        result.playerName_ = playerName_;
        result.avatarPath_ = avatarPath_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protobuf.game.GameServer.PlayerEnterGameResponse) {
          return mergeFrom((com.protobuf.game.GameServer.PlayerEnterGameResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protobuf.game.GameServer.PlayerEnterGameResponse other) {
        if (other == com.protobuf.game.GameServer.PlayerEnterGameResponse.getDefaultInstance()) return this;
        if (other.getPlayerId() != 0L) {
          setPlayerId(other.getPlayerId());
        }
        if (other.getDiamond() != 0L) {
          setDiamond(other.getDiamond());
        }
        if (other.getGold() != 0L) {
          setGold(other.getGold());
        }
        if (!other.getPlayerName().isEmpty()) {
          playerName_ = other.playerName_;
          onChanged();
        }
        if (!other.getAvatarPath().isEmpty()) {
          avatarPath_ = other.avatarPath_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protobuf.game.GameServer.PlayerEnterGameResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protobuf.game.GameServer.PlayerEnterGameResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long playerId_ ;
      /**
       * <pre>
       * 玩家id
       * </pre>
       *
       * <code>int64 playerId = 1;</code>
       */
      public long getPlayerId() {
        return playerId_;
      }
      /**
       * <pre>
       * 玩家id
       * </pre>
       *
       * <code>int64 playerId = 1;</code>
       */
      public Builder setPlayerId(long value) {
        
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 玩家id
       * </pre>
       *
       * <code>int64 playerId = 1;</code>
       */
      public Builder clearPlayerId() {
        
        playerId_ = 0L;
        onChanged();
        return this;
      }

      private long diamond_ ;
      /**
       * <pre>
       * 玩家钻石
       * </pre>
       *
       * <code>int64 diamond = 2;</code>
       */
      public long getDiamond() {
        return diamond_;
      }
      /**
       * <pre>
       * 玩家钻石
       * </pre>
       *
       * <code>int64 diamond = 2;</code>
       */
      public Builder setDiamond(long value) {
        
        diamond_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 玩家钻石
       * </pre>
       *
       * <code>int64 diamond = 2;</code>
       */
      public Builder clearDiamond() {
        
        diamond_ = 0L;
        onChanged();
        return this;
      }

      private long gold_ ;
      /**
       * <pre>
       * 玩家金币
       * </pre>
       *
       * <code>int64 gold = 3;</code>
       */
      public long getGold() {
        return gold_;
      }
      /**
       * <pre>
       * 玩家金币
       * </pre>
       *
       * <code>int64 gold = 3;</code>
       */
      public Builder setGold(long value) {
        
        gold_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 玩家金币
       * </pre>
       *
       * <code>int64 gold = 3;</code>
       */
      public Builder clearGold() {
        
        gold_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object playerName_ = "";
      /**
       * <pre>
       * 玩家昵称
       * </pre>
       *
       * <code>string playerName = 4;</code>
       */
      public java.lang.String getPlayerName() {
        java.lang.Object ref = playerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          playerName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 玩家昵称
       * </pre>
       *
       * <code>string playerName = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPlayerNameBytes() {
        java.lang.Object ref = playerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          playerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 玩家昵称
       * </pre>
       *
       * <code>string playerName = 4;</code>
       */
      public Builder setPlayerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        playerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 玩家昵称
       * </pre>
       *
       * <code>string playerName = 4;</code>
       */
      public Builder clearPlayerName() {
        
        playerName_ = getDefaultInstance().getPlayerName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 玩家昵称
       * </pre>
       *
       * <code>string playerName = 4;</code>
       */
      public Builder setPlayerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        playerName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object avatarPath_ = "";
      /**
       * <pre>
       * 头像路径
       * </pre>
       *
       * <code>string avatarPath = 5;</code>
       */
      public java.lang.String getAvatarPath() {
        java.lang.Object ref = avatarPath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          avatarPath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 头像路径
       * </pre>
       *
       * <code>string avatarPath = 5;</code>
       */
      public com.google.protobuf.ByteString
          getAvatarPathBytes() {
        java.lang.Object ref = avatarPath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          avatarPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 头像路径
       * </pre>
       *
       * <code>string avatarPath = 5;</code>
       */
      public Builder setAvatarPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        avatarPath_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 头像路径
       * </pre>
       *
       * <code>string avatarPath = 5;</code>
       */
      public Builder clearAvatarPath() {
        
        avatarPath_ = getDefaultInstance().getAvatarPath();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 头像路径
       * </pre>
       *
       * <code>string avatarPath = 5;</code>
       */
      public Builder setAvatarPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        avatarPath_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PlayerEnterGameResponse)
    }

    // @@protoc_insertion_point(class_scope:PlayerEnterGameResponse)
    private static final com.protobuf.game.GameServer.PlayerEnterGameResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.protobuf.game.GameServer.PlayerEnterGameResponse();
    }

    public static com.protobuf.game.GameServer.PlayerEnterGameResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerEnterGameResponse>
        PARSER = new com.google.protobuf.AbstractParser<PlayerEnterGameResponse>() {
      @java.lang.Override
      public PlayerEnterGameResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerEnterGameResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerEnterGameResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerEnterGameResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.protobuf.game.GameServer.PlayerEnterGameResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerEnterGameRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PlayerEnterGameRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerEnterGameResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PlayerEnterGameResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020gameserver.proto\"*\n\026PlayerEnterGameReq" +
      "uest\022\020\n\010playerId\030\001 \001(\003\"r\n\027PlayerEnterGam" +
      "eResponse\022\020\n\010playerId\030\001 \001(\003\022\017\n\007diamond\030\002" +
      " \001(\003\022\014\n\004gold\030\003 \001(\003\022\022\n\nplayerName\030\004 \001(\t\022\022" +
      "\n\navatarPath\030\005 \001(\tB\037\n\021com.protobuf.gameB" +
      "\nGameServerb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PlayerEnterGameRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PlayerEnterGameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PlayerEnterGameRequest_descriptor,
        new java.lang.String[] { "PlayerId", });
    internal_static_PlayerEnterGameResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PlayerEnterGameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PlayerEnterGameResponse_descriptor,
        new java.lang.String[] { "PlayerId", "Diamond", "Gold", "PlayerName", "AvatarPath", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
